version: "3.8"

services:
  db:
    image: mariadb:latest
    ports:
      - "3306:3306/tcp"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      backend:

networks:
  backend:
    attachable: true

volumes:
  db_data:
