name: Docker-Image-Upload
on:
  push:
    tags:
      - '*'
jobs:
  docker:
    name: Docker Image Upload
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - uses: actions/checkout@v1
    - name: Login to Docker Hub
      run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password-stdin <<< ${{ secrets.DOCKER_PASSWORD }}
    - name: Set tag to DOCKER_TAGS
      id: get_version
      run: echo ::set-output name=version::${GITHUB_REF:10}
    - name: Push image to Docker Hub
      run: DOCKER_TAGS=${{ steps.get_version.outputs.version }} make docker-push

